version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:3001
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/test_case
  mongo:
    image: mongo
    ports:
      - 27017:27017
